name: 'setup-k14s'
description: 'Install k14s apps'
author: 'John Brunton'
inputs:
  only:
    description: 'Which apps to download'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'dist/index.js'
