name: 'setup-k14s'
description: 'Install k14s apps'
author: 'John Brunton'
inputs:
  all:
    description: 'Whether to install all apps'
    required: false
    default: false
  kbld:
    description: 'Install kbld'
    required: false
    default: null
  ytt:
    description: 'Install ytt'
    required: false
    default: null
runs:
  using: 'node12'
  main: 'dist/index.js'
