name: test
on:
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'

jobs:
  test-e2e-all:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: check all apps installed
      run: ./test/verify-installed.sh ytt kbld kapp kwt imgpkg vendir

  test-e2e-specific:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        only: ytt, kbld
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        ./test/verify-installed.sh ytt kbld
        ./test/verify-not-installed.sh kapp kwt imgpkg vendir

  test-e2e-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        only: ytt
        ytt: v0.27.0
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: ./test/verify-version.sh ytt 0.27.0

  test-e2e-no-token:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        only: ytt
    - run: ./test/verify-installed.sh ytt
